//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _4WebApp_12._01_
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestsNumbers
    {
        public int Id { get; set; }
        public Nullable<int> Guest_Id { get; set; }
        public Nullable<int> Number_Id { get; set; }
    
        public virtual Guests Guests { get; set; }
        public virtual Numbers Numbers { get; set; }
    }
}
